

fcubs:
  username: ${FCUBS_USERNAME:TAKEON02}
  password: ${FCUBS_PASSWORD:Oracle@123}
  service: ${FCUBS_SERVICE:FCUBSAccService}
  customer-service-url: http://10.1.12.71:8101/FCUBSCustomerService/FCUBSCustomerService

  source: ${FCUBS_SOURCE:FCUBS}
  ubscomp: ${FCUBS_UBSCOMP:FCUBS}
  msgid: ${FCUBS_MSGID:3211411}
  correlid: ${FCUBS_CORRELID:}
  userid: ${FCUBS_USERID:${FCUBS_USERNAME:TAKEON02}}
  moduleid: ${FCUBS_MODULEID:}
  branch: ${FCUBS_BRANCH:100}
  operation: ${FCUBS_OPERATION:createCustomer}

server:
  port: 9080