
package com.techstack.corebanking.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FCUBSCustomerServiceSEI", targetNamespace = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSCustomerServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSECUSTOMERFSFSRES
     */
    @WebMethod(operationName = "CloseCustomerFS")
    @WebResult(name = "CLOSECUSTOMER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustomerFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustomerFSResponse")
    public CLOSECUSTOMERFSFSRES closeCustomerFS(
        @WebParam(name = "CLOSECUSTOMER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSECUSTOMERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSEAMTBLKFSFSRES
     */
    @WebMethod(operationName = "CloseAmtBlkFS")
    @WebResult(name = "CLOSEAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseAmtBlkFSResponse")
    public CLOSEAMTBLKFSFSRES closeAmtBlkFS(
        @WebParam(name = "CLOSEAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSEAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZEAMTBLKFSFSRES
     */
    @WebMethod(operationName = "AuthorizeAmtBlkFS")
    @WebResult(name = "AUTHORIZEAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeAmtBlkFSResponse")
    public AUTHORIZEAMTBLKFSFSRES authorizeAmtBlkFS(
        @WebParam(name = "AUTHORIZEAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZEAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYNSFCBENQIOFSRES
     */
    @WebMethod(operationName = "QueryNSFCBenqIO")
    @WebResult(name = "QUERYNSFCBENQ_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryNSFCBenqIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryNSFCBenqIOResponse")
    public QUERYNSFCBENQIOFSRES queryNSFCBenqIO(
        @WebParam(name = "QUERYNSFCBENQ_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYNSFCBENQIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYNSFCHECKIOFSRES
     */
    @WebMethod(operationName = "QueryNSFCheckIO")
    @WebResult(name = "QUERYNSFCHECK_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryNSFCheckIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryNSFCheckIOResponse")
    public QUERYNSFCHECKIOFSRES queryNSFCheckIO(
        @WebParam(name = "QUERYNSFCHECK_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYNSFCHECKIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYNSFMUTUALIOFSRES
     */
    @WebMethod(operationName = "QueryNSFMutualIO")
    @WebResult(name = "QUERYNSFMUTUAL_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryNSFMutualIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryNSFMutualIOResponse")
    public QUERYNSFMUTUALIOFSRES queryNSFMutualIO(
        @WebParam(name = "QUERYNSFMUTUAL_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYNSFMUTUALIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYTDAMOUNTBLOCKIOFSRES
     */
    @WebMethod(operationName = "QueryTDAmountBlockIO")
    @WebResult(name = "QUERYTDAMOUNTBLOCK_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryTDAmountBlockIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryTDAmountBlockIOResponse")
    public QUERYTDAMOUNTBLOCKIOFSRES queryTDAmountBlockIO(
        @WebParam(name = "QUERYTDAMOUNTBLOCK_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYTDAMOUNTBLOCKIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENAMTBLKFSFSRES
     */
    @WebMethod(operationName = "ReopenAmtBlkFS")
    @WebResult(name = "REOPENAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenAmtBlkFSResponse")
    public REOPENAMTBLKFSFSRES reopenAmtBlkFS(
        @WebParam(name = "REOPENAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENAMTBLKIOPKRES
     */
    @WebMethod(operationName = "ReopenAmtBlkIO")
    @WebResult(name = "REOPENAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenAmtBlkIOResponse")
    public REOPENAMTBLKIOPKRES reopenAmtBlkIO(
        @WebParam(name = "REOPENAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENCONSOLAMTBLKFSFSRES
     */
    @WebMethod(operationName = "ReopenConsolAmtBlkFS")
    @WebResult(name = "REOPENCONSOLAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenConsolAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenConsolAmtBlkFSResponse")
    public REOPENCONSOLAMTBLKFSFSRES reopenConsolAmtBlkFS(
        @WebParam(name = "REOPENCONSOLAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENCONSOLAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENCONSOLAMTBLKIOPKRES
     */
    @WebMethod(operationName = "ReopenConsolAmtBlkIO")
    @WebResult(name = "REOPENCONSOLAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenConsolAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenConsolAmtBlkIOResponse")
    public REOPENCONSOLAMTBLKIOPKRES reopenConsolAmtBlkIO(
        @WebParam(name = "REOPENCONSOLAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENCONSOLAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENCUSTSEGASSOCIATIONFSFSRES
     */
    @WebMethod(operationName = "ReopenCustSegAssociationFS")
    @WebResult(name = "REOPENCUSTSEGASSOCIATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustSegAssociationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustSegAssociationFSResponse")
    public REOPENCUSTSEGASSOCIATIONFSFSRES reopenCustSegAssociationFS(
        @WebParam(name = "REOPENCUSTSEGASSOCIATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENCUSTSEGASSOCIATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENCUSTSEGASSOCIATIONIOPKRES
     */
    @WebMethod(operationName = "ReopenCustSegAssociationIO")
    @WebResult(name = "REOPENCUSTSEGASSOCIATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustSegAssociationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustSegAssociationIOResponse")
    public REOPENCUSTSEGASSOCIATIONIOPKRES reopenCustSegAssociationIO(
        @WebParam(name = "REOPENCUSTSEGASSOCIATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENCUSTSEGASSOCIATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENCUSTOMERFSFSRES
     */
    @WebMethod(operationName = "ReopenCustomerFS")
    @WebResult(name = "REOPENCUSTOMER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustomerFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustomerFSResponse")
    public REOPENCUSTOMERFSFSRES reopenCustomerFS(
        @WebParam(name = "REOPENCUSTOMER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENCUSTOMERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENCUSTOMERIOPKRES
     */
    @WebMethod(operationName = "ReopenCustomerIO")
    @WebResult(name = "REOPENCUSTOMER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustomerIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenCustomerIOResponse")
    public REOPENCUSTOMERIOPKRES reopenCustomerIO(
        @WebParam(name = "REOPENCUSTOMER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENCUSTOMERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENTDAMOUNTBLOCKFSFSRES
     */
    @WebMethod(operationName = "ReopenTDAmountBlockFS")
    @WebResult(name = "REOPENTDAMOUNTBLOCK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenTDAmountBlockFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenTDAmountBlockFSResponse")
    public REOPENTDAMOUNTBLOCKFSFSRES reopenTDAmountBlockFS(
        @WebParam(name = "REOPENTDAMOUNTBLOCK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENTDAMOUNTBLOCKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.REOPENTDAMOUNTBLOCKIOPKRES
     */
    @WebMethod(operationName = "ReopenTDAmountBlockIO")
    @WebResult(name = "REOPENTDAMOUNTBLOCK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenTDAmountBlockIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ReopenTDAmountBlockIOResponse")
    public REOPENTDAMOUNTBLOCKIOPKRES reopenTDAmountBlockIO(
        @WebParam(name = "REOPENTDAMOUNTBLOCK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        REOPENTDAMOUNTBLOCKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECLOSUREDATAIOPKRES
     */
    @WebMethod(operationName = "AuthorizeClosureDataIO")
    @WebResult(name = "AUTHORIZECLOSUREDATA_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeClosureDataIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeClosureDataIOResponse")
    public AUTHORIZECLOSUREDATAIOPKRES authorizeClosureDataIO(
        @WebParam(name = "AUTHORIZECLOSUREDATA_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECLOSUREDATAIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECONSOLAMTBLKIOPKRES
     */
    @WebMethod(operationName = "AuthorizeConsolAmtBlkIO")
    @WebResult(name = "AUTHORIZECONSOLAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeConsolAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeConsolAmtBlkIOResponse")
    public AUTHORIZECONSOLAMTBLKIOPKRES authorizeConsolAmtBlkIO(
        @WebParam(name = "AUTHORIZECONSOLAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECONSOLAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECONSOLAMTBLKFSFSRES
     */
    @WebMethod(operationName = "AuthorizeConsolAmtBlkFS")
    @WebResult(name = "AUTHORIZECONSOLAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeConsolAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeConsolAmtBlkFSResponse")
    public AUTHORIZECONSOLAMTBLKFSFSRES authorizeConsolAmtBlkFS(
        @WebParam(name = "AUTHORIZECONSOLAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECONSOLAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECUSTOMERFSFSRES
     */
    @WebMethod(operationName = "CreateCustomerFS")
    @WebResult(name = "CREATECUSTOMER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerFSResponse")
    public CREATECUSTOMERFSFSRES createCustomerFS(
        @WebParam(name = "CREATECUSTOMER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECUSTOMERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZETDAMOUNTBLOCKFSFSRES
     */
    @WebMethod(operationName = "AuthorizeTDAmountBlockFS")
    @WebResult(name = "AUTHORIZETDAMOUNTBLOCK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeTDAmountBlockFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeTDAmountBlockFSResponse")
    public AUTHORIZETDAMOUNTBLOCKFSFSRES authorizeTDAmountBlockFS(
        @WebParam(name = "AUTHORIZETDAMOUNTBLOCK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZETDAMOUNTBLOCKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSECUSTSEGASSOCIATIONIOPKRES
     */
    @WebMethod(operationName = "CloseCustSegAssociationIO")
    @WebResult(name = "CLOSECUSTSEGASSOCIATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustSegAssociationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustSegAssociationIOResponse")
    public CLOSECUSTSEGASSOCIATIONIOPKRES closeCustSegAssociationIO(
        @WebParam(name = "CLOSECUSTSEGASSOCIATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSECUSTSEGASSOCIATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECUSTOMERFSFSRES
     */
    @WebMethod(operationName = "AuthorizeCustomerFS")
    @WebResult(name = "AUTHORIZECUSTOMER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustomerFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustomerFSResponse")
    public AUTHORIZECUSTOMERFSFSRES authorizeCustomerFS(
        @WebParam(name = "AUTHORIZECUSTOMER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECUSTOMERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATEAMTBLKIOPKRES
     */
    @WebMethod(operationName = "CreateAmtBlkIO")
    @WebResult(name = "CREATEAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAmtBlkIOResponse")
    public CREATEAMTBLKIOPKRES createAmtBlkIO(
        @WebParam(name = "CREATEAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATEAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECUSTOMERIOPKRES
     */
    @WebMethod(operationName = "AuthorizeCustomerIO")
    @WebResult(name = "AUTHORIZECUSTOMER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustomerIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustomerIOResponse")
    public AUTHORIZECUSTOMERIOPKRES authorizeCustomerIO(
        @WebParam(name = "AUTHORIZECUSTOMER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECUSTOMERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSECONSOLAMTBLKIOPKRES
     */
    @WebMethod(operationName = "CloseConsolAmtBlkIO")
    @WebResult(name = "CLOSECONSOLAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseConsolAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseConsolAmtBlkIOResponse")
    public CLOSECONSOLAMTBLKIOPKRES closeConsolAmtBlkIO(
        @WebParam(name = "CLOSECONSOLAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSECONSOLAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSECONSOLAMTBLKFSFSRES
     */
    @WebMethod(operationName = "CloseConsolAmtBlkFS")
    @WebResult(name = "CLOSECONSOLAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseConsolAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseConsolAmtBlkFSResponse")
    public CLOSECONSOLAMTBLKFSFSRES closeConsolAmtBlkFS(
        @WebParam(name = "CLOSECONSOLAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSECONSOLAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSETDAMOUNTBLOCKIOPKRES
     */
    @WebMethod(operationName = "CloseTDAmountBlockIO")
    @WebResult(name = "CLOSETDAMOUNTBLOCK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseTDAmountBlockIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseTDAmountBlockIOResponse")
    public CLOSETDAMOUNTBLOCKIOPKRES closeTDAmountBlockIO(
        @WebParam(name = "CLOSETDAMOUNTBLOCK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSETDAMOUNTBLOCKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCONSOLAMTBLKIOPKRES
     */
    @WebMethod(operationName = "ModifyConsolAmtBlkIO")
    @WebResult(name = "MODIFYCONSOLAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyConsolAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyConsolAmtBlkIOResponse")
    public MODIFYCONSOLAMTBLKIOPKRES modifyConsolAmtBlkIO(
        @WebParam(name = "MODIFYCONSOLAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCONSOLAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCUSTSEGASSOCIATIONFSFSRES
     */
    @WebMethod(operationName = "ModifyCustSegAssociationFS")
    @WebResult(name = "MODIFYCUSTSEGASSOCIATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustSegAssociationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustSegAssociationFSResponse")
    public MODIFYCUSTSEGASSOCIATIONFSFSRES modifyCustSegAssociationFS(
        @WebParam(name = "MODIFYCUSTSEGASSOCIATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCUSTSEGASSOCIATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCUSTSEGASSOCIATIONIOPKRES
     */
    @WebMethod(operationName = "ModifyCustSegAssociationIO")
    @WebResult(name = "MODIFYCUSTSEGASSOCIATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustSegAssociationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustSegAssociationIOResponse")
    public MODIFYCUSTSEGASSOCIATIONIOPKRES modifyCustSegAssociationIO(
        @WebParam(name = "MODIFYCUSTSEGASSOCIATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCUSTSEGASSOCIATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCUSTOMERFSFSRES
     */
    @WebMethod(operationName = "ModifyCustomerFS")
    @WebResult(name = "MODIFYCUSTOMER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerFSResponse")
    public MODIFYCUSTOMERFSFSRES modifyCustomerFS(
        @WebParam(name = "MODIFYCUSTOMER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCUSTOMERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCUSTOMERIOPKRES
     */
    @WebMethod(operationName = "ModifyCustomerIO")
    @WebResult(name = "MODIFYCUSTOMER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerIOResponse")
    public MODIFYCUSTOMERIOPKRES modifyCustomerIO(
        @WebParam(name = "MODIFYCUSTOMER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCUSTOMERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCUSTOMEROBLIGATIONFSFSRES
     */
    @WebMethod(operationName = "ModifyCustomerObligationFS")
    @WebResult(name = "MODIFYCUSTOMEROBLIGATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerObligationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerObligationFSResponse")
    public MODIFYCUSTOMEROBLIGATIONFSFSRES modifyCustomerObligationFS(
        @WebParam(name = "MODIFYCUSTOMEROBLIGATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCUSTOMEROBLIGATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCUSTOMEROBLIGATIONIOPKRES
     */
    @WebMethod(operationName = "ModifyCustomerObligationIO")
    @WebResult(name = "MODIFYCUSTOMEROBLIGATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerObligationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyCustomerObligationIOResponse")
    public MODIFYCUSTOMEROBLIGATIONIOPKRES modifyCustomerObligationIO(
        @WebParam(name = "MODIFYCUSTOMEROBLIGATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCUSTOMEROBLIGATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYFATCAFSFSRES
     */
    @WebMethod(operationName = "ModifyFATCAFS")
    @WebResult(name = "MODIFYFATCA_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyFATCAFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyFATCAFSResponse")
    public MODIFYFATCAFSFSRES modifyFATCAFS(
        @WebParam(name = "MODIFYFATCA_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYFATCAFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYFATCAIOPKRES
     */
    @WebMethod(operationName = "ModifyFATCAIO")
    @WebResult(name = "MODIFYFATCA_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyFATCAIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyFATCAIOResponse")
    public MODIFYFATCAIOPKRES modifyFATCAIO(
        @WebParam(name = "MODIFYFATCA_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYFATCAIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYNSFMUTUALFSFSRES
     */
    @WebMethod(operationName = "ModifyNSFMutualFS")
    @WebResult(name = "MODIFYNSFMUTUAL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyNSFMutualFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyNSFMutualFSResponse")
    public MODIFYNSFMUTUALFSFSRES modifyNSFMutualFS(
        @WebParam(name = "MODIFYNSFMUTUAL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYNSFMUTUALFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYNSFMUTUALIOPKRES
     */
    @WebMethod(operationName = "ModifyNSFMutualIO")
    @WebResult(name = "MODIFYNSFMUTUAL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyNSFMutualIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyNSFMutualIOResponse")
    public MODIFYNSFMUTUALIOPKRES modifyNSFMutualIO(
        @WebParam(name = "MODIFYNSFMUTUAL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYNSFMUTUALIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYTDAMOUNTBLOCKFSFSRES
     */
    @WebMethod(operationName = "ModifyTDAmountBlockFS")
    @WebResult(name = "MODIFYTDAMOUNTBLOCK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyTDAmountBlockFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyTDAmountBlockFSResponse")
    public MODIFYTDAMOUNTBLOCKFSFSRES modifyTDAmountBlockFS(
        @WebParam(name = "MODIFYTDAMOUNTBLOCK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYTDAMOUNTBLOCKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYTDAMOUNTBLOCKIOPKRES
     */
    @WebMethod(operationName = "ModifyTDAmountBlockIO")
    @WebResult(name = "MODIFYTDAMOUNTBLOCK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyTDAmountBlockIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyTDAmountBlockIOResponse")
    public MODIFYTDAMOUNTBLOCKIOPKRES modifyTDAmountBlockIO(
        @WebParam(name = "MODIFYTDAMOUNTBLOCK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYTDAMOUNTBLOCKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYACCOUNTSTRUCTUREIOFSRES
     */
    @WebMethod(operationName = "QueryAccountStructureIO")
    @WebResult(name = "QUERYACCOUNTSTRUCTURE_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryAccountStructureIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryAccountStructureIOResponse")
    public QUERYACCOUNTSTRUCTUREIOFSRES queryAccountStructureIO(
        @WebParam(name = "QUERYACCOUNTSTRUCTURE_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYACCOUNTSTRUCTUREIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYAMTBLKIOFSRES
     */
    @WebMethod(operationName = "QueryAmtBlkIO")
    @WebResult(name = "QUERYAMTBLK_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryAmtBlkIOResponse")
    public QUERYAMTBLKIOFSRES queryAmtBlkIO(
        @WebParam(name = "QUERYAMTBLK_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYAMTBLKIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYBLKIOFSRES
     */
    @WebMethod(operationName = "QueryBlkIO")
    @WebResult(name = "QUERYBLK_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryBlkIOResponse")
    public QUERYBLKIOFSRES queryBlkIO(
        @WebParam(name = "QUERYBLK_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYBLKIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCLOSUREDATAIOFSRES
     */
    @WebMethod(operationName = "QueryClosureDataIO")
    @WebResult(name = "QUERYCLOSUREDATA_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryClosureDataIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryClosureDataIOResponse")
    public QUERYCLOSUREDATAIOFSRES queryClosureDataIO(
        @WebParam(name = "QUERYCLOSUREDATA_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCLOSUREDATAIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCONSOLAMTBLKIOFSRES
     */
    @WebMethod(operationName = "QueryConsolAmtBlkIO")
    @WebResult(name = "QUERYCONSOLAMTBLK_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryConsolAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryConsolAmtBlkIOResponse")
    public QUERYCONSOLAMTBLKIOFSRES queryConsolAmtBlkIO(
        @WebParam(name = "QUERYCONSOLAMTBLK_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCONSOLAMTBLKIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCUSTACCDETAILIOFSRES
     */
    @WebMethod(operationName = "QueryCustAccDetailIO")
    @WebResult(name = "QUERYCUSTACCDETAIL_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustAccDetailIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustAccDetailIOResponse")
    public QUERYCUSTACCDETAILIOFSRES queryCustAccDetailIO(
        @WebParam(name = "QUERYCUSTACCDETAIL_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCUSTACCDETAILIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCUSTSEGASSOCIATIONIOFSRES
     */
    @WebMethod(operationName = "QueryCustSegAssociationIO")
    @WebResult(name = "QUERYCUSTSEGASSOCIATION_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustSegAssociationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustSegAssociationIOResponse")
    public QUERYCUSTSEGASSOCIATIONIOFSRES queryCustSegAssociationIO(
        @WebParam(name = "QUERYCUSTSEGASSOCIATION_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCUSTSEGASSOCIATIONIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCUSTSIGNIMGEIOFSRES
     */
    @WebMethod(operationName = "QueryCustSignImgeIO")
    @WebResult(name = "QUERYCUSTSIGNIMGE_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustSignImgeIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustSignImgeIOResponse")
    public QUERYCUSTSIGNIMGEIOFSRES queryCustSignImgeIO(
        @WebParam(name = "QUERYCUSTSIGNIMGE_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCUSTSIGNIMGEIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCUSTOMERIOFSRES
     */
    @WebMethod(operationName = "QueryCustomerIO")
    @WebResult(name = "QUERYCUSTOMER_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustomerIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustomerIOResponse")
    public QUERYCUSTOMERIOFSRES queryCustomerIO(
        @WebParam(name = "QUERYCUSTOMER_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCUSTOMERIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCUSTOMERDETAILSIOFSRES
     */
    @WebMethod(operationName = "QueryCustomerDetailsIO")
    @WebResult(name = "QUERYCUSTOMERDETAILS_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustomerDetailsIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustomerDetailsIOResponse")
    public QUERYCUSTOMERDETAILSIOFSRES queryCustomerDetailsIO(
        @WebParam(name = "QUERYCUSTOMERDETAILS_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCUSTOMERDETAILSIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYCUSTOMEROBLIGATIONIOFSRES
     */
    @WebMethod(operationName = "QueryCustomerObligationIO")
    @WebResult(name = "QUERYCUSTOMEROBLIGATION_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustomerObligationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryCustomerObligationIOResponse")
    public QUERYCUSTOMEROBLIGATIONIOFSRES queryCustomerObligationIO(
        @WebParam(name = "QUERYCUSTOMEROBLIGATION_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYCUSTOMEROBLIGATIONIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.QUERYFATCAIOFSRES
     */
    @WebMethod(operationName = "QueryFATCAIO")
    @WebResult(name = "QUERYFATCA_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryFATCAIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/QueryFATCAIOResponse")
    public QUERYFATCAIOFSRES queryFATCAIO(
        @WebParam(name = "QUERYFATCA_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        QUERYFATCAIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSECUSTSEGASSOCIATIONFSFSRES
     */
    @WebMethod(operationName = "CloseCustSegAssociationFS")
    @WebResult(name = "CLOSECUSTSEGASSOCIATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustSegAssociationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustSegAssociationFSResponse")
    public CLOSECUSTSEGASSOCIATIONFSFSRES closeCustSegAssociationFS(
        @WebParam(name = "CLOSECUSTSEGASSOCIATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSECUSTSEGASSOCIATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECUSTSEGASSOCIATIONFSFSRES
     */
    @WebMethod(operationName = "AuthorizeCustSegAssociationFS")
    @WebResult(name = "AUTHORIZECUSTSEGASSOCIATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustSegAssociationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustSegAssociationFSResponse")
    public AUTHORIZECUSTSEGASSOCIATIONFSFSRES authorizeCustSegAssociationFS(
        @WebParam(name = "AUTHORIZECUSTSEGASSOCIATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECUSTSEGASSOCIATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSETDAMOUNTBLOCKFSFSRES
     */
    @WebMethod(operationName = "CloseTDAmountBlockFS")
    @WebResult(name = "CLOSETDAMOUNTBLOCK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseTDAmountBlockFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseTDAmountBlockFSResponse")
    public CLOSETDAMOUNTBLOCKFSFSRES closeTDAmountBlockFS(
        @WebParam(name = "CLOSETDAMOUNTBLOCK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSETDAMOUNTBLOCKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATEAMTBLKFSFSRES
     */
    @WebMethod(operationName = "CreateAmtBlkFS")
    @WebResult(name = "CREATEAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAmtBlkFSResponse")
    public CREATEAMTBLKFSFSRES createAmtBlkFS(
        @WebParam(name = "CREATEAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATEAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECLOSUREDATAFSFSRES
     */
    @WebMethod(operationName = "AuthorizeClosureDataFS")
    @WebResult(name = "AUTHORIZECLOSUREDATA_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeClosureDataFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeClosureDataFSResponse")
    public AUTHORIZECLOSUREDATAFSFSRES authorizeClosureDataFS(
        @WebParam(name = "AUTHORIZECLOSUREDATA_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECLOSUREDATAFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZETDAMOUNTBLOCKIOPKRES
     */
    @WebMethod(operationName = "AuthorizeTDAmountBlockIO")
    @WebResult(name = "AUTHORIZETDAMOUNTBLOCK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeTDAmountBlockIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeTDAmountBlockIOResponse")
    public AUTHORIZETDAMOUNTBLOCKIOPKRES authorizeTDAmountBlockIO(
        @WebParam(name = "AUTHORIZETDAMOUNTBLOCK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZETDAMOUNTBLOCKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZEAMTBLKIOPKRES
     */
    @WebMethod(operationName = "AuthorizeAmtBlkIO")
    @WebResult(name = "AUTHORIZEAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeAmtBlkIOResponse")
    public AUTHORIZEAMTBLKIOPKRES authorizeAmtBlkIO(
        @WebParam(name = "AUTHORIZEAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZEAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETECUSTOMERFSFSRES
     */
    @WebMethod(operationName = "DeleteCustomerFS")
    @WebResult(name = "DELETECUSTOMER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustomerFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustomerFSResponse")
    public DELETECUSTOMERFSFSRES deleteCustomerFS(
        @WebParam(name = "DELETECUSTOMER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETECUSTOMERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETECUSTOMERIOPKRES
     */
    @WebMethod(operationName = "DeleteCustomerIO")
    @WebResult(name = "DELETECUSTOMER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustomerIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustomerIOResponse")
    public DELETECUSTOMERIOPKRES deleteCustomerIO(
        @WebParam(name = "DELETECUSTOMER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETECUSTOMERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETEFATCAFSFSRES
     */
    @WebMethod(operationName = "DeleteFATCAFS")
    @WebResult(name = "DELETEFATCA_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteFATCAFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteFATCAFSResponse")
    public DELETEFATCAFSFSRES deleteFATCAFS(
        @WebParam(name = "DELETEFATCA_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETEFATCAFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETEFATCAIOPKRES
     */
    @WebMethod(operationName = "DeleteFATCAIO")
    @WebResult(name = "DELETEFATCA_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteFATCAIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteFATCAIOResponse")
    public DELETEFATCAIOPKRES deleteFATCAIO(
        @WebParam(name = "DELETEFATCA_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETEFATCAIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETETDAMOUNTBLOCKFSFSRES
     */
    @WebMethod(operationName = "DeleteTDAmountBlockFS")
    @WebResult(name = "DELETETDAMOUNTBLOCK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteTDAmountBlockFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteTDAmountBlockFSResponse")
    public DELETETDAMOUNTBLOCKFSFSRES deleteTDAmountBlockFS(
        @WebParam(name = "DELETETDAMOUNTBLOCK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETETDAMOUNTBLOCKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETETDAMOUNTBLOCKIOPKRES
     */
    @WebMethod(operationName = "DeleteTDAmountBlockIO")
    @WebResult(name = "DELETETDAMOUNTBLOCK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteTDAmountBlockIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteTDAmountBlockIOResponse")
    public DELETETDAMOUNTBLOCKIOPKRES deleteTDAmountBlockIO(
        @WebParam(name = "DELETETDAMOUNTBLOCK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETETDAMOUNTBLOCKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYACCOUNTSTRUCTUREFSFSRES
     */
    @WebMethod(operationName = "ModifyAccountStructureFS")
    @WebResult(name = "MODIFYACCOUNTSTRUCTURE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAccountStructureFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAccountStructureFSResponse")
    public MODIFYACCOUNTSTRUCTUREFSFSRES modifyAccountStructureFS(
        @WebParam(name = "MODIFYACCOUNTSTRUCTURE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYACCOUNTSTRUCTUREFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYACCOUNTSTRUCTUREIOPKRES
     */
    @WebMethod(operationName = "ModifyAccountStructureIO")
    @WebResult(name = "MODIFYACCOUNTSTRUCTURE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAccountStructureIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAccountStructureIOResponse")
    public MODIFYACCOUNTSTRUCTUREIOPKRES modifyAccountStructureIO(
        @WebParam(name = "MODIFYACCOUNTSTRUCTURE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYACCOUNTSTRUCTUREIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYAMTBLKFSFSRES
     */
    @WebMethod(operationName = "ModifyAmtBlkFS")
    @WebResult(name = "MODIFYAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAmtBlkFSResponse")
    public MODIFYAMTBLKFSFSRES modifyAmtBlkFS(
        @WebParam(name = "MODIFYAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYAMTBLKIOPKRES
     */
    @WebMethod(operationName = "ModifyAmtBlkIO")
    @WebResult(name = "MODIFYAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyAmtBlkIOResponse")
    public MODIFYAMTBLKIOPKRES modifyAmtBlkIO(
        @WebParam(name = "MODIFYAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCLOSUREDATAFSFSRES
     */
    @WebMethod(operationName = "ModifyClosureDataFS")
    @WebResult(name = "MODIFYCLOSUREDATA_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyClosureDataFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyClosureDataFSResponse")
    public MODIFYCLOSUREDATAFSFSRES modifyClosureDataFS(
        @WebParam(name = "MODIFYCLOSUREDATA_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCLOSUREDATAFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCLOSUREDATAIOPKRES
     */
    @WebMethod(operationName = "ModifyClosureDataIO")
    @WebResult(name = "MODIFYCLOSUREDATA_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyClosureDataIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyClosureDataIOResponse")
    public MODIFYCLOSUREDATAIOPKRES modifyClosureDataIO(
        @WebParam(name = "MODIFYCLOSUREDATA_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCLOSUREDATAIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.MODIFYCONSOLAMTBLKFSFSRES
     */
    @WebMethod(operationName = "ModifyConsolAmtBlkFS")
    @WebResult(name = "MODIFYCONSOLAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyConsolAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/ModifyConsolAmtBlkFSResponse")
    public MODIFYCONSOLAMTBLKFSFSRES modifyConsolAmtBlkFS(
        @WebParam(name = "MODIFYCONSOLAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        MODIFYCONSOLAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECLOSUREDATAIOPKRES
     */
    @WebMethod(operationName = "CreateClosureDataIO")
    @WebResult(name = "CREATECLOSUREDATA_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateClosureDataIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateClosureDataIOResponse")
    public CREATECLOSUREDATAIOPKRES createClosureDataIO(
        @WebParam(name = "CREATECLOSUREDATA_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECLOSUREDATAIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECONSOLAMTBLKFSFSRES
     */
    @WebMethod(operationName = "CreateConsolAmtBlkFS")
    @WebResult(name = "CREATECONSOLAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateConsolAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateConsolAmtBlkFSResponse")
    public CREATECONSOLAMTBLKFSFSRES createConsolAmtBlkFS(
        @WebParam(name = "CREATECONSOLAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECONSOLAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECONSOLAMTBLKIOPKRES
     */
    @WebMethod(operationName = "CreateConsolAmtBlkIO")
    @WebResult(name = "CREATECONSOLAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateConsolAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateConsolAmtBlkIOResponse")
    public CREATECONSOLAMTBLKIOPKRES createConsolAmtBlkIO(
        @WebParam(name = "CREATECONSOLAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECONSOLAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECUSTSEGASSOCIATIONFSFSRES
     */
    @WebMethod(operationName = "CreateCustSegAssociationFS")
    @WebResult(name = "CREATECUSTSEGASSOCIATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustSegAssociationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustSegAssociationFSResponse")
    public CREATECUSTSEGASSOCIATIONFSFSRES createCustSegAssociationFS(
        @WebParam(name = "CREATECUSTSEGASSOCIATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECUSTSEGASSOCIATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECUSTSEGASSOCIATIONIOPKRES
     */
    @WebMethod(operationName = "CreateCustSegAssociationIO")
    @WebResult(name = "CREATECUSTSEGASSOCIATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustSegAssociationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustSegAssociationIOResponse")
    public CREATECUSTSEGASSOCIATIONIOPKRES createCustSegAssociationIO(
        @WebParam(name = "CREATECUSTSEGASSOCIATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECUSTSEGASSOCIATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATENSFMUTUALIOPKRES
     */
    @WebMethod(operationName = "CreateNSFMutualIO")
    @WebResult(name = "CREATENSFMUTUAL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateNSFMutualIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateNSFMutualIOResponse")
    public CREATENSFMUTUALIOPKRES createNSFMutualIO(
        @WebParam(name = "CREATENSFMUTUAL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATENSFMUTUALIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATETDAMOUNTBLOCKFSFSRES
     */
    @WebMethod(operationName = "CreateTDAmountBlockFS")
    @WebResult(name = "CREATETDAMOUNTBLOCK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateTDAmountBlockFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateTDAmountBlockFSResponse")
    public CREATETDAMOUNTBLOCKFSFSRES createTDAmountBlockFS(
        @WebParam(name = "CREATETDAMOUNTBLOCK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATETDAMOUNTBLOCKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATETDAMOUNTBLOCKIOPKRES
     */
    @WebMethod(operationName = "CreateTDAmountBlockIO")
    @WebResult(name = "CREATETDAMOUNTBLOCK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateTDAmountBlockIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateTDAmountBlockIOResponse")
    public CREATETDAMOUNTBLOCKIOPKRES createTDAmountBlockIO(
        @WebParam(name = "CREATETDAMOUNTBLOCK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATETDAMOUNTBLOCKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETEAMTBLKFSFSRES
     */
    @WebMethod(operationName = "DeleteAmtBlkFS")
    @WebResult(name = "DELETEAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteAmtBlkFSResponse")
    public DELETEAMTBLKFSFSRES deleteAmtBlkFS(
        @WebParam(name = "DELETEAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETEAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETEAMTBLKIOPKRES
     */
    @WebMethod(operationName = "DeleteAmtBlkIO")
    @WebResult(name = "DELETEAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteAmtBlkIOResponse")
    public DELETEAMTBLKIOPKRES deleteAmtBlkIO(
        @WebParam(name = "DELETEAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETEAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETECONSOLAMTBLKFSFSRES
     */
    @WebMethod(operationName = "DeleteConsolAmtBlkFS")
    @WebResult(name = "DELETECONSOLAMTBLK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteConsolAmtBlkFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteConsolAmtBlkFSResponse")
    public DELETECONSOLAMTBLKFSFSRES deleteConsolAmtBlkFS(
        @WebParam(name = "DELETECONSOLAMTBLK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETECONSOLAMTBLKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETECONSOLAMTBLKIOPKRES
     */
    @WebMethod(operationName = "DeleteConsolAmtBlkIO")
    @WebResult(name = "DELETECONSOLAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteConsolAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteConsolAmtBlkIOResponse")
    public DELETECONSOLAMTBLKIOPKRES deleteConsolAmtBlkIO(
        @WebParam(name = "DELETECONSOLAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETECONSOLAMTBLKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETECUSTSEGASSOCIATIONFSFSRES
     */
    @WebMethod(operationName = "DeleteCustSegAssociationFS")
    @WebResult(name = "DELETECUSTSEGASSOCIATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustSegAssociationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustSegAssociationFSResponse")
    public DELETECUSTSEGASSOCIATIONFSFSRES deleteCustSegAssociationFS(
        @WebParam(name = "DELETECUSTSEGASSOCIATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETECUSTSEGASSOCIATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.DELETECUSTSEGASSOCIATIONIOPKRES
     */
    @WebMethod(operationName = "DeleteCustSegAssociationIO")
    @WebResult(name = "DELETECUSTSEGASSOCIATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustSegAssociationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/DeleteCustSegAssociationIOResponse")
    public DELETECUSTSEGASSOCIATIONIOPKRES deleteCustSegAssociationIO(
        @WebParam(name = "DELETECUSTSEGASSOCIATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        DELETECUSTSEGASSOCIATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSECUSTOMERIOPKRES
     */
    @WebMethod(operationName = "CloseCustomerIO")
    @WebResult(name = "CLOSECUSTOMER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustomerIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseCustomerIOResponse")
    public CLOSECUSTOMERIOPKRES closeCustomerIO(
        @WebParam(name = "CLOSECUSTOMER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSECUSTOMERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.AUTHORIZECUSTSEGASSOCIATIONIOPKRES
     */
    @WebMethod(operationName = "AuthorizeCustSegAssociationIO")
    @WebResult(name = "AUTHORIZECUSTSEGASSOCIATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustSegAssociationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/AuthorizeCustSegAssociationIOResponse")
    public AUTHORIZECUSTSEGASSOCIATIONIOPKRES authorizeCustSegAssociationIO(
        @WebParam(name = "AUTHORIZECUSTSEGASSOCIATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        AUTHORIZECUSTSEGASSOCIATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATEACCOUNTSTRUCTUREFSFSRES
     */
    @WebMethod(operationName = "CreateAccountStructureFS")
    @WebResult(name = "CREATEACCOUNTSTRUCTURE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAccountStructureFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAccountStructureFSResponse")
    public CREATEACCOUNTSTRUCTUREFSFSRES createAccountStructureFS(
        @WebParam(name = "CREATEACCOUNTSTRUCTURE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATEACCOUNTSTRUCTUREFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATEACCOUNTSTRUCTUREIOPKRES
     */
    @WebMethod(operationName = "CreateAccountStructureIO")
    @WebResult(name = "CREATEACCOUNTSTRUCTURE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAccountStructureIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateAccountStructureIOResponse")
    public CREATEACCOUNTSTRUCTUREIOPKRES createAccountStructureIO(
        @WebParam(name = "CREATEACCOUNTSTRUCTURE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATEACCOUNTSTRUCTUREIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECLOSUREDATAFSFSRES
     */
    @WebMethod(operationName = "CreateClosureDataFS")
    @WebResult(name = "CREATECLOSUREDATA_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateClosureDataFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateClosureDataFSResponse")
    public CREATECLOSUREDATAFSFSRES createClosureDataFS(
        @WebParam(name = "CREATECLOSUREDATA_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECLOSUREDATAFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECUSTOMERIOPKRES
     */
    @WebMethod(operationName = "CreateCustomerIO")
    @WebResult(name = "CREATECUSTOMER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerIOResponse")
    public CREATECUSTOMERIOPKRES createCustomerIO(
        @WebParam(name = "CREATECUSTOMER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECUSTOMERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECUSTOMEROBLIGATIONFSFSRES
     */
    @WebMethod(operationName = "CreateCustomerObligationFS")
    @WebResult(name = "CREATECUSTOMEROBLIGATION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerObligationFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerObligationFSResponse")
    public CREATECUSTOMEROBLIGATIONFSFSRES createCustomerObligationFS(
        @WebParam(name = "CREATECUSTOMEROBLIGATION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECUSTOMEROBLIGATIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATECUSTOMEROBLIGATIONIOPKRES
     */
    @WebMethod(operationName = "CreateCustomerObligationIO")
    @WebResult(name = "CREATECUSTOMEROBLIGATION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerObligationIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateCustomerObligationIOResponse")
    public CREATECUSTOMEROBLIGATIONIOPKRES createCustomerObligationIO(
        @WebParam(name = "CREATECUSTOMEROBLIGATION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATECUSTOMEROBLIGATIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATEFATCAFSFSRES
     */
    @WebMethod(operationName = "CreateFATCAFS")
    @WebResult(name = "CREATEFATCA_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateFATCAFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateFATCAFSResponse")
    public CREATEFATCAFSFSRES createFATCAFS(
        @WebParam(name = "CREATEFATCA_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATEFATCAFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATEFATCAIOPKRES
     */
    @WebMethod(operationName = "CreateFATCAIO")
    @WebResult(name = "CREATEFATCA_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateFATCAIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateFATCAIOResponse")
    public CREATEFATCAIOPKRES createFATCAIO(
        @WebParam(name = "CREATEFATCA_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATEFATCAIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CREATENSFMUTUALFSFSRES
     */
    @WebMethod(operationName = "CreateNSFMutualFS")
    @WebResult(name = "CREATENSFMUTUAL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateNSFMutualFSRequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CreateNSFMutualFSResponse")
    public CREATENSFMUTUALFSFSRES createNSFMutualFS(
        @WebParam(name = "CREATENSFMUTUAL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CREATENSFMUTUALFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.techstack.corebanking.stub.CLOSEAMTBLKIOPKRES
     */
    @WebMethod(operationName = "CloseAmtBlkIO")
    @WebResult(name = "CLOSEAMTBLK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseAmtBlkIORequest", output = "http://FCUBSCustomerService.types.ws.gw.fcubs.ofss.com/FCUBSCustomerServiceSEI/CloseAmtBlkIOResponse")
    public CLOSEAMTBLKIOPKRES closeAmtBlkIO(
        @WebParam(name = "CLOSEAMTBLK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCustomerService", partName = "RequestMsg")
        CLOSEAMTBLKIOPKREQ requestMsg);

}
